In [20]:
import pandas as pd
import numpy as np
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)

In [21]:
with open("../data/final_dataset/list_dict_with_tasks.pkl", "rb") as file:
    loaded_list = pickle.load(file)

In [22]:
df = pd.DataFrame(loaded_list)
df = df.sort_values("id").reset_index(drop=True)

df.head()

,id,topic,subtopic,complexity_level,problem,solution,answer
0,30262,Алгебра и арифметика,Арифметика. Устный счет и т.п,2,"Из книги выпал кусок, первая страница которого...",,496 страниц (248 листов)
1,30289,Алгебра и арифметика,Четность и нечетность,2,Можно ли доску размером 5×5 заполнить доминошк...,"Общее количество клеток (25) не делится на 2, ...",Нельзя
2,30320,Комбинаторика,Правило произведения,2,Монету бросают трижды. Сколько разных последов...,,2<sup>3</sup> = 8 последовательностей
3,30321,Комбинаторика,Правило произведения,2,Каждую клетку квадратной таблицы 2×2 можно пок...,,16 = 2<sup>4</sup> раскрасок
4,30322,Комбинаторика,Правило произведения,2,Сколькими способами можно заполнить одну карто...,,3<sup>13</sup> способами

In [23]:
df.topic.str.lower().unique(), df.complexity_level_text.str.lower().unique()

AttributeError: 'DataFrame' object has no attribute 'complexity_level_text'

In [24]:
df['complexity_level_text'] = df['complexity_level'].map({'2-': 'Легкий',
                                                          '2': 'Легкий',
                                                          '2+': 'Средний',
                                                          '3-': 'Средний',
                                                          '3': 'Сложный',
                                                          '3+': 'Сложный'})

In [25]:
(
    df.complexity_level.value_counts().sort_index(),
    df.complexity_level_text.value_counts().sort_index()
)

(complexity_level
 2     30
 2+    27
 2-     9
 3     35
 3+    33
 3-    13
 Name: count, dtype: int64,
 complexity_level_text
 Легкий     39
 Сложный    68
 Средний    40
 Name: count, dtype: int64)

In [26]:
reverted_list = df.to_dict('records')

In [27]:
with open("../data/final_dataset/list_dict_with_tasks_update.pkl", "wb") as file:
    pickle.dump(reverted_list, file)

In [28]:
with open("../static_dataset/list_dict_with_tasks_update.pkl", "wb") as file:
    pickle.dump(reverted_list, file)

In [31]:
df

,id,topic,subtopic,complexity_level,problem,solution,answer,complexity_level_text
0,30262,Алгебра и арифметика,Арифметика. Устный счет и т.п,2,"Из книги выпал кусок, первая страница которого...",,496 страниц (248 листов),Легкий
1,30289,Алгебра и арифметика,Четность и нечетность,2,Можно ли доску размером 5×5 заполнить доминошк...,"Общее количество клеток (25) не делится на 2, ...",Нельзя,Легкий
2,30320,Комбинаторика,Правило произведения,2,Монету бросают трижды. Сколько разных последов...,,2<sup>3</sup> = 8 последовательностей,Легкий
3,30321,Комбинаторика,Правило произведения,2,Каждую клетку квадратной таблицы 2×2 можно пок...,,16 = 2<sup>4</sup> раскрасок,Легкий
4,30322,Комбинаторика,Правило произведения,2,Сколькими способами можно заполнить одну карто...,,3<sup>13</sup> способами,Легкий
5,30325,Комбинаторика,Правило произведения,2,Сколькими способами можно сделать трёхцветный ...,Цвет для верхней полоски флага можно выбрать ш...,120 способами,Легкий
6,30341,Комбинаторика,Правило произведения,2,"Сколько существует шестизначных чисел, все циф...",,9·5<sup>5</sup> чисел,Легкий
7,30346,Комбинаторика,Перестановки и подстановки (прочее),2,На танцплощадке собрались N юношей и N девушек...,,N ! способами,Легкий
8,30364,Олимпиадные задачи,Произведения и факториалы,2+,На сколько нулей оканчивается число 100!?,"Необходимо найти, сколько пар простых чисел 2 ...",На 24 нуля,Средний
9,30419,Комбинаторика,Степень вершины,2,"В государстве 100 городов, и из каждого из них...",,100·4 : 2 = 200,Легкий
10,30431,Комбинаторика,Обход графов,2,"Имеется группа островов, соединённых мостами т...",а) На Троекратый турист 3 раза зашёл и 3 раза ...,а) 6 мостов; б) 5 мостов; в) 4 моста,Легкий
11,30690,Комбинаторика,Сочетания и размещения,2+,"У одного школьника есть 6 книг по математике, ...",Первый школьник может выбрать 3 книги для обме...,1120 способами,Средний
12,30697,Комбинаторика,Сочетания и размещения,2+,Сколькими способами можно составить комиссию и...,,4·2<sup>3</sup> = 32 способами,Средний
13,30699,Комбинаторика,Сочетания и размещения,2+,Сколькими способами можно переставить буквы сл...,,C_{3}^{7} = 35 способами,Средний
14,30722,Комбинаторика,Сочетания и размещения,2+,"Сколькими способами можно разрезать ожерелье, ...","Нужно указать 8 мест из 30, в которых будут пр...",C_{30}^{8} способами,Средний
15,30778,Комбинаторика,Четность перестановки,3,"В ряд выписаны числа 1, 2, 3, ..., n . За один...","Каждая пара ( a, b ) чисел может находиться в ...",Не может,Сложный
16,30832,Алгебра и арифметика,Системы счисления,2,В какой системе счисления справедливо равенств...,,В 12-ричной,Легкий
17,30862,Алгебра и арифметика,Неравенство Коши,2,"Докажите, что ½ ( x ² + y ²) ≥ xy при любых x ...","Перегруппировав члены, получаем ½ ( x – y )² ≥ 0.",,Легкий
18,30937,Алгебра и арифметика,Четность и нечетность,2,Чётно или нечётно число 1 + 2 + 3 + ... + 1990?,,Нечётно,Легкий
19,30941,Алгебра и арифметика,Четность и нечетность,2,У каждого марсианина три руки. Могут ли семь м...,Всего рук 21 – нечётное число. Если бы они взя...,Не могут,Легкий
20,31083,Комбинаторика,Теория графов (прочее),2,"В классе больше 32, но меньше 40 человек. Кажд...",Количество рёбер в соответствующем графе в три...,Такого класса не существует,Легкий
21,31235,Алгебра и арифметика,Арифметика остатков (прочее),2,Найти последнюю цифру числа 1·2 + 2·3 + ... + ...,1·2 + 2·3 + ... + 999·1000 ≡ 1·2 + 2·3 + ... +...,0,Легкий
22,32052,Комбинаторика,Классическая комбинаторика (прочее),3-,Было семь ящиков. В некоторые из них положили ...,При каждой операции заполняется один пустой ящ...,,Средний
23,32830,Алгебра и арифметика,Задачи на проценты и отношения,2,В течение года цены на штрюдели два раза подни...,После первого повышения цен штрюдель стал стои...,90 рублей,Легкий
24,32838,Алгебра и арифметика,Задачи на движение,2,Вадим и Лёша спускались с горы. Вадим шёл пешк...,Леша шёл пешком с половины горы столько же вре...,Вадим,Легкий
25,34848,Алгебра и арифметика,Свойства коэффициентов многочлена,2+,Найдите сумму всех коэффициентов многочлена ( ...,"Эта сумма равна значению многочлена при x = 1,...",1,Средний
26,34872,Математический анализ,Непрерывные функции (общие свойства),3,"О функции f ( x ), заданной на всей вещественн...",По условию функции f ( x ) + f (4 x ) и f ( x ...,,Сложный
27,34938,Алгебра и арифметика,Разложение на множители,2+,Какие остатки могут получиться при делении n ³...,n ³ + 3 = ( n + 1)( n ² – n + 1) + 2.,Только 2,Средний
28,35012,Алгебра и арифметика,Признаки делимости на 3 и 9,2,"Известно, что 35! = 10333147966386144929*66651...","Поскольку 35! делится на 9, сумма цифр этого ч...",6,Легкий
29,35071,Комбинаторика,НОД и НОК. Взаимная простота,3,"Сколько существует пар натуральных чисел, у ко...",Рассмотрим две возможности. 1) Одно из чисел р...,32 пары,Сложный
30,35129,Комбинаторика,Комбинаторика (прочее),3,"Трое играют в настольный теннис, причем игрок,...","По условию второй игрок сыграл 21 партию, поэт...",11 партий,Сложный
31,35178,Вероятность и статистика,Парадоксы,3,Каждый вечер Иван Таранов приходит в случайное...,"Рассмотрим следующий пример. Пусть маршрут A, ...",,Сложный
32,35306,Алгебра и арифметика,Системы линейных уравнений,2+,Решите систему уравнений 5732 x + 2134 y + 213...,"Складывая уравнения, получим x + y + z = 2 или...","(1, –1, 2)",Средний
33,35352,Вероятность и статистика,Теория вероятностей (прочее),3+,При посадке в самолет выстроилась очередь из n...,Пусть при некоторой рассадке пассажиров послед...,0.50,Сложный
34,35399,Комбинаторика,Сочетания и размещения,3+,Имеется 20 человек – 10 юношей и 10 девушек. С...,Пусть имеется некоторая компания из k юношей и...,C_{20}^{10} = 184756 способов,Сложный
35,35479,Комбинаторика,Комбинаторика (прочее),3,За круглым столом расселись 10 мальчиков и 15 ...,Группы сидящих подряд мальчиков чередуются с г...,10 пар,Сложный
36,35532,Алгебра и арифметика,Задачи на проценты и отношения,3+,"Автобус называется переполненным , если в нем ...",Окрасим переполненные автобусы в красный цвет....,Процент пассажиров больше,Сложный
37,35641,Алгебра и арифметика,Симметрические системы. Инволютивные преобразо...,3,Существуют ли три различных действительных чис...,"Пусть a, b, c – такие числа, что a + bc = b + ...",Не существуют,Сложный
38,35676,Алгебра и арифметика,Математическая логика (прочее),2+,Пусть x - некоторое натуральное число. Среди у...,"Первое утверждение эквивалентно тому, что x &g...",9.00,Средний
39,35734,Комбинаторика,Степень вершины,3+,"В классе 20 учеников, причём каждый дружит не ...",Соберём весь класс в одной комнате. Рассмотрим...,Можно,Сложный
40,60336,Комбинаторика,Правило произведения,2,Cколько существует различных семизначных телеф...,"Первую цифру можно выбрать 9 способами, а кажд...",9·10<sup>6</sup> номеров,Легкий
41,60345,Комбинаторика,Правило произведения,3,Пассажир оставил вещи в автоматической камере ...,Разберём несколько случаев. 1) Номер содержит ...,356 номеров,Сложный
42,60370,Комбинаторика,Перестановки и подстановки (прочее),2,В пассажирском поезде 17 вагонов. Сколькими сп...,,17! способами,Легкий
43,60378,Комбинаторика,Сочетания и размещения,2+,Сколькими способами можно выбрать четырёх чело...,,A_{9}^{4} = 9 * 8 * 7 * 6 = 3024 способами,Средний
44,60381,Комбинаторика,Сочетания и размещения,2,На плоскости дано n точек. Сколько имеется отр...,,C_{n}^{2},Легкий
45,60382,Комбинаторика,Сочетания и размещения,2+,На плоскости дано n прямых общего положения. Ч...,,C_{n}^{3},Средний
46,60384,Комбинаторика,Сочетания и размещения,3+,Международная комиссия состоит из девяти челов...,"По условию, любые пять человек сейф открыть не...","126 замков, по 4 ключа к каждому замку",Сложный
47,60402,Комбинаторика,Сочетания и размещения,2+,"Сколько существует шестизначных чисел, у котор...",<b>Первый способ.</b> Каждому такому числу одн...,C_{10}^{6} = C_{10}^{4} = 210 чисел,Средний
48,60403,Комбинаторика,Сочетания и размещения,3-,"Имеется m белых и n чёрных шаров, причём m &gt...",Из m + 1 позиции ( m – 1 промежуток между белы...,C_{m+1}^{n} способами,Средний
49,60450,Комбинаторика,Числа Каталана,3+,"Билеты стоят 50 центов, и 2 n покупателей стоя...",,C <sub> n </sub>,Сложный
50,60652,Алгебра и арифметика,Разложение на множители,2+,"Докажите, что числа а) 2<sup>3<sup>2001</sup><...",2<sup>3 k </sup> + 1 делится на 2<sup> k </sup...,,Средний
51,60976,Алгебра и арифметика,Теорема Безу. Разложение на множители,3+,При каких a и b многочлен P ( x ) = ( a + b ) ...,x <sup>2</sup> – 3 x + 2 = ( x – 1)( x – 2). П...,"{ a, b } = {–1, <sup>31</sup>/<sub>28</sub>}",Сложный
52,61199,Алгебра и арифметика,Тригонометрия (прочее),2+,Вычислите следующие произведения: а) <!-- MAT...,,а) 3/16; б) 1/16,Средний
53,61213,Математический анализ,Тригонометрия (прочее),3,Найдите наибольшее и наименьшее значения функ...,,,Сложный
54,61219,Алгебра и арифметика,Тождественные преобразования (тригонометрия),3,Найдите наибольшее и наименьшее значение функ...,,"Наибольшее значение — 1, наименьшее — 1/4",Сложный
55,61221,Алгебра и арифметика,Тригонометрические уравнения,3-,Решите уравнение <!-- MATH $\sin x+\sin 2x+\s...,,,Средний
56,61222,Алгебра и арифметика,Тригонометрические уравнения,3+,Решите уравнение <!-- MATH $\hbox{\rm tg\ }x+...,,,Сложный
57,64511,Комбинаторика,Десятичная система счисления,3+,Володя хочет сделать набор кубиков одного разм...,"Нужно не менее 30 единиц, двоек, ..., девяток ...",50 кубиков,Сложный
58,64670,Алгебра и арифметика,Турниры и турнирные таблицы,3+,"В турнире по игре в ""крестики – нолики"", прове...","Всего в турнире было сыграно 17 партий, так ка...",Ошибается,Сложный
59,64671,Алгебра и арифметика,Алгебраические уравнения и системы уравнений (...,3+,Число a – корень уравнения х <sup>11</sup> + х...,"Подстановкой в уравнение убеждаемся в том, что...",При n = 15,Сложный
60,64822,Алгебра и арифметика,Квадратные уравнения. Формула корней,2+,Решите уравнение: x ( x + 1) = 2014·2015.,"Данное уравнение – квадратное, поэтому имеет н...","x <sub>1</sub> = 2014, x <sub>2</sub> = –2015",Средний
61,64824,Алгебра и арифметика,Текстовые задачи (прочее),3,"Три пирата нашли клад, состоящий из 240 золоты...","Пусть один из слитков стоит 121 доллар, а кажд...",Может,Сложный
62,64833,Комбинаторика,Теория алгоритмов (прочее),3+,В строку выписаны 40 знаков: 20 крестиков и 20...,"Для того чтобы 20 крестиков стояли подряд, нео...",За 200 ходов,Сложный
63,64891,Математический анализ,Функции. Непрерывность (прочее),2+,"Числовая функция f такова, что для любых x и y...","f (0,5) = f (0,25 + 0,25) = f (0,25) + f (0,25...",38,Средний
64,64948,Алгебра и арифметика,Турниры и турнирные таблицы,3,В круговом шахматном турнире участвовало шесть...,В круговом турнире из шести участников разыгры...,Не могли,Сложный
65,64960,Алгебра и арифметика,Тригонометрические неравенства,3,"Не используя калькулятора, определите знак чис...","Функция y = sin x возрастает на отрезке [0, <s...",Это число отрицательно,Сложный
66,65265,Вероятность и статистика,Дискретное распределение,3+,Петя предлагает Васе сыграть в следующую игру....,Поскольку Вася вынет две карамельки с вероятно...,У Пети,Сложный
67,65267,Вероятность и статистика,Дискретное распределение,3+,Имеются два симметричных кубика. Можно ли так ...,Приведём пример таких кубиков. Пусть на первом...,Можно,Сложный
68,65312,Вероятность и статистика,Математическая статистика,3,В числовом наборе 100 чисел. Если выкинуть одн...,Расположим числа в порядке возрастания. Если в...,72,Сложный
69,65315,Вероятность и статистика,Дискретное распределение,3,40% приверженцев некоторой политической партии...,"Пусть событие A ""приверженец – женщина"", а B –...",Являются,Сложный
70,65330,Вероятность и статистика,Математическая статистика,3-,"В наборе –5, –4, –3, –2, –1, 0, 1, 2, 3, 4, 5 ...","Как известно, дисперсия набора равна разности ...",Надо заменить –4 на 1 и –5 или заменить 4 на –...,Средний
71,65333,Вероятность и статистика,Дискретное распределение,3+,"Петр Иванович, еще 49 мужчин и 50 женщин в слу...","а) Петр Иванович недоволен, только если по обе...",а) <sup>25</sup>/<sub>33</sub>; б) 37<sup>29</...,Сложный
72,65344,Комбинаторика,Классическая комбинаторика (прочее),2+,В кабинете министров Анчурии 100 министров. Ср...,Честных министров не больше чем девять: десятк...,91,Средний
73,65425,Алгебра и арифметика,Системы линейных уравнений,3+,"Сумма трёх различных чисел равна 10, а разност...","Пусть a + b + c = 10, a &gt; b &gt; c, a – c =...",<sup>73</sup>/<sub>3</sub> &lt; b &lt; <sup>13...,Сложный
74,65636,Алгебра и арифметика,Текстовые задачи (прочее),3+,Артемон подарил Мальвине букет из аленьких цве...,"Заметим, что у каждого цветка число тычинок в ...",216 тычинок,Сложный
75,65768,Вероятность и статистика,Дискретное распределение,3+,К юбилею Санкт-Петербургских математических ол...,"Известно, что выпал орёл. Значит, была выбрана...",⅔,Сложный
76,65785,Вероятность и статистика,Дискретное распределение,3+,"Билет на электричку стоит 50 рублей, а штраф з...","Пусть вероятность покупки билета p , а вероятн...",Все равно,Сложный
77,65965,Алгебра и арифметика,Системы алгебраических нелинейных уравнений,3+,"Решите систему уравнений: x ³ – y = 6, y ³ – z...","Если x ≥ y , то y = x ³ – 6 ≥ y ³ – 6 = z . Ан...","(2, 2, 2)",Сложный
78,65985,Алгебра и арифметика,Арифметическая прогрессия,3+,"(sin x , sin y , sin z ) – возрастающая арифме...","Предположим, что (cos x , cos y , cos z ) – ар...",Не может,Сложный
79,65987,Алгебра и арифметика,Уравнения в целых числах,3+,"Число 1047 при делении на A дает остаток 23, а...",Так как 1047 даёт остаток 23 при делении на А ...,64,Сложный
80,66034,Вероятность и статистика,Математическая статистика,3-,"Найдите медиану набора длин: 2 м 30 см, 250 мм...",,240 см,Средний
81,66038,Вероятность и статистика,Непрерывное распределение,2+,Для тестирования новой программы компьютер выб...,,"0,8",Средний
82,66354,Математический анализ,Функции. Непрерывность (прочее),3+,Для всех действительных x и y выполняется раве...,"Подставив x = 0, y = 0, получим f (0) = f (0) ...",0,Сложный
83,66360,Алгебра и арифметика,Уравнения высших степеней (прочее),3,Число p – корень кубического уравнения x ³ + x...,"Из условия следует, что p ³ + p = 3. Значит, (...",x ³ + 2 x ² + x – 9 = 0,Сложный
84,66576,Комбинаторика,Текстовые задачи (прочее),3,"За круглым вращающимся столом, на котором стоя...",Рассмотрим произвольную расстановку чашек и вы...,7,Сложный
85,66720,Комбинаторика,Замощения костями домино и плитками,3+,Петя расставляет 500 королей на клетках доски ...,Каждой Петиной расстановке поставим в соответс...,У Васи,Сложный
86,67400,Алгебра и арифметика,Задачи на движение,3,"На часах три стрелки, каждая вращается в ту же...",Контрпример. Пусть длинная стрелка за час дела...,Не обязательно,Сложный
87,67443,Олимпиадные задачи,Арифметические действия. Числовые тождества,3,"На доске написаны два натуральных числа, одно ...",Разность этих чисел может равняться <span clas...,"Да, может",Сложный
88,67455,Олимпиадные задачи,Логика и теория множеств (прочее),3,Герцог Сумматор выбрал некоторые вещественные ...,"Пусть <span class=""MathJax_Preview"" style=""dis...","Да, обязательно",Сложный
89,76414,Олимпиадные задачи,Квадратные уравнения и системы уравнений,2,"Определить отношение двух чисел, если отношени...","Пусть <span class=""MathJax_Preview"" style=""dis...",16 : 9 или 9 : 16,Легкий
90,76429,Олимпиадные задачи,Системы алгебраических нелинейных уравнений,2+,Сколько действительных решений имеет система д...,( x – y )² + 4 z ² = ( x + y )² – 4( xy – z ²)...,Одно решение,Средний
91,76430,Алгебра и арифметика,Системы алгебраических нелинейных уравнений,3+,"Решить систему уравнений: x ³ – y ³ = 26, x ² ...","( x – y )³ = x ³ – y ³ – 3( x ² y – xy ²) = 8,...","(3, 1), (–1, –3)",Сложный
92,76501,Алгебра и арифметика,Разложение на множители,2+,Разделить a <sup>128</sup> – b <sup>128</sup> ...,,a – b,Средний
93,77964,Олимпиадные задачи,Числовые таблицы и их свойства,2+,200 учеников выстроены прямоугольником по 10 ч...,"Пусть A – самый низкий среди высоких, B – самы...",Самый низкий среди высоких (если они разного р...,Средний
94,78008,Алгебра и арифметика,Тригонометрические уравнения,3+,Найти все действительные решения уравнения x ²...,Рассмотрим данное уравнение как квадратное ура...,"x = ±1, y = – <sup>π</sup>/<sub>2</sub> + 2 k π",Сложный
95,78025,Олимпиадные задачи,"Медиана, проведенная к гипотенузе",2+,Дан прямоугольный треугольник ABC . Из вершины...,"Точка K делит AD пополам, поэтому AB = BD . Та...","30°, 60°",Средний
96,78159,Алгебра и арифметика,Уравнения в целых числах,3+,Решить в натуральных числах уравнение x <sup>2...,x <sup>2 y –1</sup> ≡ 1 (mod x + 1). Поскольку...,x = y = 1,Сложный
97,78489,Олимпиадные задачи,Раскладки и разбиения,3-,Завод выпускает погремушки в виде кольца с над...,Красные шарики в кольце делят синие на три гру...,8 погремушек,Средний
98,78726,Олимпиадные задачи,Шахматные доски и шахматные фигуры,2+,На бесконечной шахматной доске на двух соседни...,При каждом взятии чёрной шашки белая шашка пер...,Нельзя,Средний
99,86483,Алгебра и арифметика,Задачи на работу,3+,На дне озера бьют ключи. Стадо из 183 слонов м...,"37 слонов за пять дней выпивают столько же, ск...",За 365 дней,Сложный
100,87981,Алгебра и арифметика,Десятичная система счисления,2-,"Попробуйте найти все натуральные числа, которы...",При умножении на 5 последняя цифра не изменила...,25,Легкий
101,87992,Алгебра и арифметика,Десятичная система счисления,2-,Одно трехзначное число состоит из различных ци...,"Эти числа, соответственно, 147 и 111. Задача р...",147 и 111,Легкий
102,88078,Алгебра и арифметика,Задачи на проценты и отношения,2,Перед началом Олимпиады хоккейные шайбы подоро...,"0,9·1,1 = 0,99. Значит, до подорожания шайбы с...",До подорожания,Легкий
103,88081,Алгебра и арифметика,Десятичная система счисления,2-,Напишите в строчку первые 10 простых чисел. Ка...,"Вот первые десять простых чисел, записанных по...",Получится число 7317192329,Легкий
104,88105,Алгебра и арифметика,Арифметическая прогрессия,2-,Делится ли на 1999 сумма чисел <!-- MATH $1+2+...,"Да, делится, поскольку <!-- MATH \begin{displa...",Да,Легкий
105,88129,Алгебра и арифметика,Задачи на движение,2-,"У Буратино и Пьеро был велосипед, на котором о...","Буратино проехал на велосипеде полдороги, слез...",,Легкий
106,88142,Алгебра и арифметика,Десятичная система счисления,2-,"Найдите наибольшее шестизначное число, у котор...","Если первая буква была a , а вторая — b , то т...",303369,Легкий
107,88246,Алгебра и арифметика,Деление с остатком,2-,"Изменятся ли частное и остаток, если делимое и...","Частное не изменится, а остаток увеличится втр...","Частное не изменится, остаток изменится, если ...",Легкий
108,89919,Алгебра и арифметика,Четность и нечетность,2-,Чётными или нечётными будут сумма и произведен...,,"а) Чётными; б) сумма чётна, произведение нечёт...",Легкий
109,98427,Математический анализ,Периодичность и непериодичность,3,В ряд стоят 1999 чисел. Первое число равно 1. ...,"Обозначим наши числа через a <sub>1</sub>, a <...",1,Сложный
110,98470,Комбинаторика,Примеры и контрпримеры. Конструкции,3+,Можно ли расставить в вершинах куба натуральны...,"Отметим четыре вершины куба, никакие две из ко...",Можно,Сложный
111,102999,Комбинаторика,Арифметика. Устный счет и т.п,2,– У меня зазвонил телефон. – Кто говорит? – Сл...,"Всего телефонных аппаратов 7, каждый соединен ...",21 провод,Легкий
112,103822,Алгебра и арифметика,Задачи на проценты и отношения,3-,В тесте к каждому вопросу указаны пять вариант...,Двоечник ошибся в половине вопросов. При этом ...,⅜,Средний
113,104102,Алгебра и арифметика,Монотонность и ограниченность,3,Решите систему уравнений: x ² + 4sin² y – 4 = ...,"2cos² y = cos x – 1 ≤ 0, откуда cos² y = 0, si...","x = 0, y = <sup>π</sup>/<sub>2</sub> + k π",Сложный
114,104122,Алгебра и арифметика,Арифметика. Устный счет и т.п,2-,Женя не успел влезть в лифт на первом этаже до...,,8 минут,Легкий

In [30]:
reverted_list

[{'id': 30262,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Арифметика. Устный счет и т.п',
  'complexity_level': '2',
  'problem': 'Из книги выпал кусок, первая страница которого имеет номер 439, а номер последней записывается теми же цифрами в каком-то другом порядке. Сколько страниц в выпавшем куске?',
  'solution': '',
  'answer': '496 страниц (248 листов)',
  'complexity_level_text': 'Легкий'},
 {'id': 30289,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Четность и нечетность',
  'complexity_level': '2',
  'problem': 'Можно ли доску размером 5×5 заполнить доминошками размером 1×2?',
  'solution': 'Общее количество клеток (25) не делится на 2, а каждая доминошка покрывает две клетки.',
  'answer': 'Нельзя',
  'complexity_level_text': 'Легкий'},
 {'id': 30320,
  'topic': 'Комбинаторика',
  'subtopic': 'Правило произведения',
  'complexity_level': '2',
  'problem': 'Монету бросают трижды. Сколько разных последовательностей орлов и решек можно при этом получить?',
  'solution': '',
  'answer': '2<sup>3</sup> = 8 последовательностей',
  'complexity_level_text': 'Легкий'},
 {'id': 30321,
  'topic': 'Комбинаторика',
  'subtopic': 'Правило произведения',
  'complexity_level': '2',
  'problem': 'Каждую клетку квадратной таблицы 2×2 можно покрасить в чёрный или белый цвет. Сколько существует различных раскрасок этой таблицы?',
  'solution': '',
  'answer': '16 = 2<sup>4</sup> раскрасок',
  'complexity_level_text': 'Легкий'},
 {'id': 30322,
  'topic': 'Комбинаторика',
  'subtopic': 'Правило произведения',
  'complexity_level': '2',
  'problem': 'Сколькими способами можно заполнить одну карточку в лотерее "Спортпрогноз"? (В этой лотерее нужно предсказать итог тринадцати спортивных матчей. Итог каждого матча – победа одной из команд либо ничья; счёт роли не играет).',
  'solution': '',
  'answer': '3<sup>13</sup> способами',
  'complexity_level_text': 'Легкий'},
 {'id': 30325,
  'topic': 'Комбинаторика',
  'subtopic': 'Правило произведения',
  'complexity_level': '2',
  'problem': 'Сколькими способами можно сделать трёхцветный флаг с горизонтальными полосами одинаковой ширины, если имеется материя шести различных цветов?',
  'solution': 'Цвет для верхней полоски флага можно выбрать шестью разными способами. После этого для средней полоски флага остается пять возможных цветов, а затем для нижней полоски флага – четыре различных цвета. Таким образом, флаг можно сделать 6·5·4 = 120 способами.',
  'answer': '120 способами',
  'complexity_level_text': 'Легкий'},
 {'id': 30341,
  'topic': 'Комбинаторика',
  'subtopic': 'Правило произведения',
  'complexity_level': '2',
  'problem': 'Сколько существует шестизначных чисел, все цифры которых имеют одинаковую чётность?',
  'solution': '',
  'answer': '9·5<sup>5</sup> чисел',
  'complexity_level_text': 'Легкий'},
 {'id': 30346,
  'topic': 'Комбинаторика',
  'subtopic': 'Перестановки и подстановки (прочее)',
  'complexity_level': '2',
  'problem': 'На танцплощадке собрались N юношей и N девушек. Сколькими способами они могут разбиться на пары для участия в очередном танце?',
  'solution': '',
  'answer': 'N ! способами',
  'complexity_level_text': 'Легкий'},
 {'id': 30364,
  'topic': 'Олимпиадные задачи',
  'subtopic': 'Произведения и факториалы',
  'complexity_level': '2+',
  'problem': 'На сколько нулей оканчивается число 100!?',
  'solution': 'Необходимо найти, сколько пар простых чисел 2 и 5 найдётся в разложении числа 100! на простые множители. В разложении 100! двоек будет больше, чем пятёрок. Поэтому достаточно найти степень, в которой 5 входит в разложение числа 100!. Среди чисел от 1 до 100 всего 20 чисел дают пятёрки в разложение, причём числа 25, 50, 75 и 100 дают сразу две пятёрки. Поэтому искомая степерь равна 24.',
  'answer': 'На 24 нуля',
  'complexity_level_text': 'Средний'},
 {'id': 30419,
  'topic': 'Комбинаторика',
  'subtopic': 'Степень вершины',
  'complexity_level': '2',
  'problem': 'В государстве 100 городов, и из каждого из них выходит 4 дороги. Сколько всего дорог в государстве?',
  'solution': '',
  'answer': '100·4 : 2 = 200',
  'complexity_level_text': 'Легкий'},
 {'id': 30431,
  'topic': 'Комбинаторика',
  'subtopic': 'Обход графов',
  'complexity_level': '2',
  'problem': 'Имеется группа островов, соединённых мостами так, что от каждого острова можно добраться до любого другого. Турист обошёл все острова, пройдя по каждому мосту ровно один раз. На острове Троекратном он побывал трижды. Сколько мостов ведёт с Троекратного, если турист а) не с него начал и не на нём закончил? б) с него начал, но не на нём закончил? в) с него начал и на нём закончил?',
  'solution': 'а) На Троекратый турист 3 раза зашёл и 3 раза с него вышел, то есть использовал 6 мостов. б) В этом случае турист зашел на остров дважды, а вышел трижды.',
  'answer': 'а) 6 мостов; б) 5 мостов; в) 4 моста',
  'complexity_level_text': 'Легкий'},
 {'id': 30690,
  'topic': 'Комбинаторика',
  'subtopic': 'Сочетания и размещения',
  'complexity_level': '2+',
  'problem': 'У одного школьника есть 6 книг по математике, а у другого – 8. Сколькими способами они могут обменять три книги одного на три книги другого?',
  'solution': 'Первый школьник может выбрать 3 книги для обмена C_{6}^{3} способами, второй - C_{3}^{8} способами. Таким образом, число возможных обменов равно C_{6}^{3} * C_{3}^{8} = 1120.',
  'answer': '1120 способами',
  'complexity_level_text': 'Средний'},
 {'id': 30697,
  'topic': 'Комбинаторика',
  'subtopic': 'Сочетания и размещения',
  'complexity_level': '2+',
  'problem': 'Сколькими способами можно составить комиссию из трёх человек, выбирая её членов из четырёх супружеских пар, но так, чтобы члены одной семьи не входили в комиссию одновременно?',
  'solution': '',
  'answer': '4·2<sup>3</sup> = 32 способами',
  'complexity_level_text': 'Средний'},
 {'id': 30699,
  'topic': 'Комбинаторика',
  'subtopic': 'Сочетания и размещения',
  'complexity_level': '2+',
  'problem': 'Сколькими способами можно переставить буквы слова "ЭПИГРАФ" так, чтобы и гласные, и согласные шли в алфавитном порядке?',
  'solution': '',
  'answer': 'C_{3}^{7} = 35 способами',
  'complexity_level_text': 'Средний'},
 {'id': 30722,
  'topic': 'Комбинаторика',
  'subtopic': 'Сочетания и размещения',
  'complexity_level': '2+',
  'problem': 'Сколькими способами можно разрезать ожерелье, состоящее из 30 различных бусин на 8 частей (резать можно только между бусинами)?',
  'solution': 'Нужно указать 8 мест из 30, в которых будут произведены разрезы.',
  'answer': 'C_{30}^{8} способами',
  'complexity_level_text': 'Средний'},
 {'id': 30778,
  'topic': 'Комбинаторика',
  'subtopic': 'Четность перестановки',
  'complexity_level': '3',
  'problem': 'В ряд выписаны числа 1, 2, 3, ..., n . За один ход разрешается поменять местами любые два числа. Может ли после 1989 таких операций порядок чисел оказаться исходным?',
  'solution': 'Каждая пара ( a, b ) чисел может находиться в двух состояниях: правильном , когда меньшее число стоит левее, и неправильном , когда меньшее число стоит правее. Если между числами a и b стоит ровно k чисел, и мы поменяем a и b местами, то ровно 2 k + 1 пара поменяет свое состояние: сама пара ( a, b ) и все пары, содержащие одно из чисел a, b и одно из k промежуточных чисел. Поэтому каждая операция меняет четность числа неправильных пар. В начале все пары были правильными. Значит после 1989 операций число неправильных пар станет нечётным . Следовательно, полученный ряд чисел не совпадает с исходным.',
  'answer': 'Не может',
  'complexity_level_text': 'Сложный'},
 {'id': 30832,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Системы счисления',
  'complexity_level': '2',
  'problem': 'В какой системе счисления справедливо равенство 3 · 4 = 10?',
  'solution': '',
  'answer': 'В 12-ричной',
  'complexity_level_text': 'Легкий'},
 {'id': 30862,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Неравенство Коши',
  'complexity_level': '2',
  'problem': 'Докажите, что ½ ( x ² + y ²) ≥ xy при любых x и y .',
  'solution': 'Перегруппировав члены, получаем ½ ( x – y )² ≥ 0.',
  'answer': '',
  'complexity_level_text': 'Легкий'},
 {'id': 30937,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Четность и нечетность',
  'complexity_level': '2',
  'problem': 'Чётно или нечётно число 1 + 2 + 3 + ... + 1990?',
  'solution': '',
  'answer': 'Нечётно',
  'complexity_level_text': 'Легкий'},
 {'id': 30941,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Четность и нечетность',
  'complexity_level': '2',
  'problem': 'У каждого марсианина три руки. Могут ли семь марсиан взяться за руки?',
  'solution': 'Всего рук 21 – нечётное число. Если бы они взялись за руки, то руки разбились бы на пары (в каждую пару входят две пожимающие друг друга руки), а это невозможно.',
  'answer': 'Не могут',
  'complexity_level_text': 'Легкий'},
 {'id': 31083,
  'topic': 'Комбинаторика',
  'subtopic': 'Теория графов (прочее)',
  'complexity_level': '2',
  'problem': 'В классе больше 32, но меньше 40 человек. Каждый мальчик дружит с тремя девочками, а каждая девочка – с пятью мальчиками. Сколько человек в классе?',
  'solution': 'Количество рёбер в соответствующем графе в три раза больше числа мальчиков и в 5 раз больше числа девочек. Следовательно, число девочек относится к числу мальчиков как 3 : 5, а общее число учеников делится на 8. Но между 32 и 40 таких чисел нет.',
  'answer': 'Такого класса не существует',
  'complexity_level_text': 'Легкий'},
 {'id': 31235,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Арифметика остатков (прочее)',
  'complexity_level': '2',
  'problem': 'Найти последнюю цифру числа 1·2 + 2·3 + ... + 999·1000.',
  'solution': '1·2 + 2·3 + ... + 999·1000 ≡ 1·2 + 2·3 + ... + 999·1000 + 1000·1001 ≡ 100(1·2 + ... + 10·11) ≡ 0 (mod 10).',
  'answer': '0',
  'complexity_level_text': 'Легкий'},
 {'id': 32052,
  'topic': 'Комбинаторика',
  'subtopic': 'Классическая комбинаторика (прочее)',
  'complexity_level': '3-',
  'problem': 'Было семь ящиков. В некоторые из них положили еще по семь ящиков (не вложенных друг в друга) и т. д. В итоге стало 10 непустых ящиков. Сколько всего стало ящиков?',
  'solution': 'При каждой операции заполняется один пустой ящик. Поскольку стало 10 непустых ящиков, то было проведено 10 операций. При каждой операции добавлялось по семь ящиков. Поэтому в результате стало 7 + 10·7 = 77 ящиков.',
  'answer': '',
  'complexity_level_text': 'Средний'},
 {'id': 32830,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Задачи на проценты и отношения',
  'complexity_level': '2',
  'problem': 'В течение года цены на штрюдели два раза поднимали на 50%, а перед Новым Годом их стали продавать за полцены. Сколько стоит сейчас один штрюдель, если в начале года он стоил 80 рублей?',
  'solution': 'После первого повышения цен штрюдель стал стоить 80·1,5 = 120 рублей; после второго повышения цен – 120·1,5 = 180 рублей; наконец, после двукратного снижения цены он стал стоить 180 : 2 = 90 рублей.',
  'answer': '90 рублей',
  'complexity_level_text': 'Легкий'},
 {'id': 32838,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Задачи на движение',
  'complexity_level': '2',
  'problem': 'Вадим и Лёша спускались с горы. Вадим шёл пешком, а Лёша съезжал на лыжах в семь раз быстрее Вадима. На полпути Лёша упал, сломал лыжи и ногу и пошёл в два раза медленней Вадима. Кто первым спустится с горы?',
  'solution': 'Леша шёл пешком с половины горы столько же времени, сколько Вадим спускался с вершины.',
  'answer': 'Вадим',
  'complexity_level_text': 'Легкий'},
 {'id': 34848,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Свойства коэффициентов многочлена',
  'complexity_level': '2+',
  'problem': 'Найдите сумму всех коэффициентов многочлена ( x ² – 3 x + 1)<sup>100</sup> после раскрытия скобок и приведения подобных членов.',
  'solution': 'Эта сумма равна значению многочлена при x = 1, то есть (1 – 3·1 + 1)<sup>100</sup> = 1.',
  'answer': '1',
  'complexity_level_text': 'Средний'},
 {'id': 34872,
  'topic': 'Математический анализ',
  'subtopic': 'Непрерывные функции (общие свойства)',
  'complexity_level': '3',
  'problem': 'О функции f ( x ), заданной на всей вещественной прямой, известно, что при любом a &gt; 1 функция f ( x ) + f ( ax ) непрерывна на всей прямой. Докажите, что f ( x ) также непрерывна на всей прямой.',
  'solution': 'По условию функции f ( x ) + f (4 x ) и f ( x ) + f (2 x ) непрерывны. Вместе с функцией f ( x ) + f (2 x ) непрерывна функция f (2 x ) + f (4 x ). Поэтому непрерывна и функция ( f ( x ) + f (2 x )) + ( f ( x ) + f (4 x )) – ( f (2 x ) + f (4 x )) = 2 f ( x ), а значит, и функция f ( x ).',
  'answer': '',
  'complexity_level_text': 'Сложный'},
 {'id': 34938,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Разложение на множители',
  'complexity_level': '2+',
  'problem': 'Какие остатки могут получиться при делении n ³ + 3 на n + 1 при натуральном n &gt; 2?',
  'solution': 'n ³ + 3 = ( n + 1)( n ² – n + 1) + 2.',
  'answer': 'Только 2',
  'complexity_level_text': 'Средний'},
 {'id': 35012,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Признаки делимости на 3 и 9',
  'complexity_level': '2',
  'problem': 'Известно, что 35! = 10333147966386144929*66651337523200000000. Найдите цифру, заменённую звездочкой.',
  'solution': 'Поскольку 35! делится на 9, сумма цифр этого числа также делится на 9. Нетрудно подсчитать, что сумма цифр (за исключением звездочки) написанного числа даёт остаток 3 при делении на 9. Отсюда следует, что цифра, замененная звездочкой, равна 6.',
  'answer': '6',
  'complexity_level_text': 'Легкий'},
 {'id': 35071,
  'topic': 'Комбинаторика',
  'subtopic': 'НОД и НОК. Взаимная простота',
  'complexity_level': '3',
  'problem': 'Сколько существует пар натуральных чисел, у которых наименьшее общее кратное (НОК) равно 2000?',
  'solution': 'Рассмотрим две возможности. 1) Одно из чисел равно 2000. Тогда другое число может быть любым делителем числа 2000. Поскольку 2000 = 2<sup>4</sup>·5<sup>3</sup>, оно имеет 20 делителей (см. задачу <a href="view_problem_details_new.php?id=30358">30358</a>). 2) Ни одно из двух чисел a, b не равно 2000. Тогда в разложении одного из этих чисел a, b (для определенности, a ) на простые сомножители должен присутствовать множитель 2<sup>4</sup>, а в разложении другого – множитель 5<sup>3</sup>. Таким образом, a = 2<sup>4</sup>·5<sup> m </sup>, b = 2<sup> n </sup>·5<sup>3</sup>, где m может принимать 3 значения (0, 1, 2) , и независимо от этого n может принимать 4 значения (0, 1, 2, 3). Таким образом, в этом случае имеется 3·4 = 12 возможностей. Итак, имеется 20 + 12 = 32 пары натуральных чисел, имеющие НОК = 2000.',
  'answer': '32 пары',
  'complexity_level_text': 'Сложный'},
 {'id': 35129,
  'topic': 'Комбинаторика',
  'subtopic': 'Комбинаторика (прочее)',
  'complexity_level': '3',
  'problem': 'Трое играют в настольный теннис, причем игрок, проигравший партию, уступает место игроку, не участвовавшему в ней. В итоге оказалось, что первый игрок сыграл 10 партий, второй – 21. Сколько партий сыграл третий игрок?',
  'solution': 'По условию второй игрок сыграл 21 партию, поэтому всего было сыграно не менее 21 партии. Из каждых двух партий подряд первый игрок хотя бы в одной должен участвовать, значит, партий было не более 2·10 + 1 = 21. Следовательно, была сыграна всего 21 партия, и второй игрок участвовал в каждой из них. В 10 партиях он встречался с первым, а в оставшихся 11 партиях – с третьим.',
  'answer': '11 партий',
  'complexity_level_text': 'Сложный'},
 {'id': 35178,
  'topic': 'Вероятность и статистика',
  'subtopic': 'Парадоксы',
  'complexity_level': '3',
  'problem': 'Каждый вечер Иван Таранов приходит в случайное время на автобусную остановку. На этой остановке останавливаются два маршрута - на одном из них Иван может ехать к себе домой, а на другом - в гости к другу Козявкину. Иван ждет первого автобуса и в зависимости от того, какой автобус подошел, он едет либо домой, либо к другу. Через некоторое время Иван заметил, что в гостях у Козявкина он оказывается при этом примерно в два раза чаще, чем дома. На основе этого Иван делает вывод, что один из автобусов ходит в два раза чаще другого. Прав ли он? Могут ли при выполнении условия задачи автобусы ходить с одинаковой частотой? (Предполагается, что автобусы ходят не случайным образом, а по некоторому расписанию.)',
  'solution': 'Рассмотрим следующий пример. Пусть маршрут A, который везет Ивана домой, приходит каждый час в 00 минут (т.е. в 0.00, 1.00, 2.00, ... ,23.00), а маршрут B, который везет к другу, приходит каждый час через 40 минут после автобуса маршрута A (т.е. в 0.40, 1,40, ... ,23.40). Таким образом, если Ваня подходит к остановке в первые 40 минут каждого часа, то он оказывается у друга, а если в последние 20 минут каждого часа (это происходит в два раза реже), то у себя дома.',
  'answer': '',
  'complexity_level_text': 'Сложный'},
 {'id': 35306,
  'topic': 'Алгебра и арифметика',
  'subtopic': 'Системы линейных уравнений',
  'complexity_level': '2+',
  'problem': 'Решите систему уравнений 5732 x + 2134 y + 2134 z = 7866, 2134 x + 5732 y + 2134 z = 670, 2134 x + 2134 y + 5732 z =11464.',
  'solution': 'Складывая уравнения, получим x + y + z = 2 или 2134( x + y + z ) = 4268. Вычитая полученную комбинацию из каждого уравнения, получим значения всех переменных.',
  'answer': '(1, –1, 2)',
  'complexity_level_text': 'Средний'},
 {'id': 35352,
  'topic': 'Вероятность и статистика',
  'subtopic': 'Теория вероятностей (прочее)',
  'complexity_level': '3+',
  'problem': 'При посадке в самолет выстроилась очередь из n пассажиров, у каждого из которых имеется билет на одно из n мест. Первой в очереди стоит сумасшедшая старушка. Она вбегает в салон и садится на случайное место (возможно, и на свое). Далее пассажиры по очереди занимают свои места, а в случае, если свое место уже занято, садятся случайным образом на одно из свободных мест. Какова вероятность того, что последний пассажир займет свое место?',
  'solution': 'Пусть при некоторой рассадке пассажиров последний пассажир сел не на свое место (такую рассадку назовем неудачной). Тогда до прихода последнего пассажира его место было занято пассажиром A (A может быть и сумасшедшей старушкой). В момент прихода пассажира A перед ним стоит выбор - какое место занять. В рассматриваемой рассадке он занимает место последнего пассажира. Но с той же вероятностью он мог занять и место старушки, и в дальнейшем все пассажиры, включая последнего, займут свои собственные места. (Конечно, нужно еще пояснить, почему в момент прихода пассажира A старушкино место все еще свободно. Но это действительно так - нетрудно проследить, что пока старушкино место свободно, среди всех еще не вошедших пассажиров есть ровно один, чье место уже занято. Как только очередной пассажир занимает старушкино место, все остальные будут садиться только на свои места.) Таким образом, каждой неудачной рассадке соответствует удачная, которая может случиться с той же вероятностью. Это говорит о том, что ровно в половине случаев рассадка будет неудачной.',
  'answer': '0.50',
  'complexity_level_text': 'Сложный'},
 {'id': 35399,
  'topic': 'Комбинаторика',
  'subtopic': 'Сочетания и размещения',
  'complexity_level': '3+',
  'problem': 'Имеется 20 человек – 10 юношей и 10 девушек. Сколько существует способов составить компанию, в которой было бы одинаковое число юношей и девушек?',
  'solution': 'Пусть имеется некоторая компания из k юношей и k девушек. Поставим ей в соответствие множество из 10 человек, в которое включим k девушек, вошедших в компанию, и 10 – k юношей, не вошедших в неё. Установленное соответствие, очевидно, является взаимно-однозначным. Таким образом, искомое число равно числу способов выбрать 10 человек из 20-ти.',
  'answer': 'C_{20}^{10} = 184756 способов',
  'complexity_level_text': 'Сложный'},
 {'id': 35479,
  'topic': 'Комбинаторика',
  'subtopic': 'Комбинаторика (прочее)',
  'complexity_level': '3',